name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: version
        run: gradle -v
      - name: Create ~/.gradle/gradle.properties
        run: |
          cat << EOS > ~/.gradle/gradle.properties
          author=rising3
          email=micho.nakagawa@gmail.com
          EOS
      - name: Build
        run: gradle build
